const crypto = require('crypto');

const CODE_SERVICE = process.env.CODE_SERVICE || 'http://localhost:5002';

async function getOctokit() {
  const token = process.env.GITHUB_TOKEN;
  if (!token) return null;
  // octokit v4+ is ESM-only; load it dynamically from CommonJS (Node >= 20).
  const { Octokit } = await import('octokit');
  return new Octokit({ auth: token });
}

function extractOwnerRepo(repoUrl) {
  try {
    const u = new URL(repoUrl);
    const parts = u.pathname.split('/').filter(Boolean);
    if (parts.length < 2) return { owner: null, repo: null };
    return { owner: parts[0], repo: parts[1].replace(/\.git$/, '') };
  } catch {
    return { owner: null, repo: null };
  }
}

async function getDefaultBranch(octokit, owner, repo) {
  const r = await octokit.rest.repos.get({ owner, repo });
  return r.data.default_branch;
}

async function createBranch(octokit, owner, repo, baseBranch, branchName) {
  const ref = await octokit.rest.git.getRef({ owner, repo, ref: `heads/${baseBranch}` });
  const sha = ref.data.object.sha;
  await octokit.rest.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha
  });
  return sha;
}

// Generate a fix for a finding: prefer the stored suggested_fix, otherwise ask
// the CodeT5 fix generator for a fresh fix. Returns a non-empty string or null.
async function resolveFix(finding, fileContent) {
  if (finding.suggested_fix && finding.suggested_fix.trim()) {
    return finding.suggested_fix;
  }
  try {
    const response = await fetch(`${CODE_SERVICE}/fix`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        code: fileContent,
        type: finding.prediction || 'unknown'
      }),
      signal: AbortSignal.timeout(60000)
    });
    if (!response.ok) return null;
    const data = await response.json();
    const fix = data && data.fix;
    if (!fix) return null;
    const trimmed = String(fix).trim();
    return trimmed ? trimmed : null;
  } catch (err) {
    return null;
  }
}

function newBranchName() {
  return `fix/auto-patch-${crypto.randomBytes(3).toString('hex')}`;
}

function buildPrBody(finding, filePath, headSha) {
  const exp = finding.explanation || {};
  const ref = exp.reference || {};
  const confidence = finding.confidence != null ? Math.round(finding.confidence * 100) : 'n/a';
  return `## 🤖 AI-Generated Auto-Fix

This PR was automatically generated by **Specula AI Security Scanner**.

### Vulnerability Detected
- **Type:** ${finding.prediction || 'unknown'}
- **Severity:** ${finding.severity || 'unknown'}
- **Confidence:** ${confidence}%

### Fix Applied
A remediated version of the vulnerable code was generated (rule-based / CodeT5) and committed to this branch.

### Files Changed
- \`${filePath}\`: applied the suggested remediation for \`${finding.prediction}\`

### ⚠️ Important
This fix was auto-generated by an AI. Please review thoroughly before merging. Automated testing is strongly recommended. Base commit: ${headSha}.

### References
- CWE: ${ref.cwe || 'N/A'}
- OWASP: ${ref.owasp || 'N/A'}

> This PR was created by the Specula autonomous security agent.
`;
}

function buildReportBody(finding, reason) {
  const exp = finding.explanation || {};
  const ref = exp.reference || {};
  const remediation = exp.remediation || {};
  const confidence = finding.confidence != null ? Math.round(finding.confidence * 100) : 'n/a';
  const manualSteps = remediation.guidance
    ? remediation.guidance
    : 'Review the affected code and apply the recommended remediation for this vulnerability class manually.';
  const suggestedCode = remediation.suggested_code_fix
    ? `\n\n\`\`\`\n${remediation.suggested_code_fix}\n\`\`\`\n`
    : '';

  return `## 🤖 Specula Security Finding (manual fix required)

An automatic fix could not be generated (${reason === 'file-not-found' ? 'the reported file was not found in the repository' : 'no reliable fix was produced for this finding'}). Manual remediation is required.

### Vulnerability Detected
- **Type:** ${finding.prediction || 'unknown'}
- **Severity:** ${finding.severity || 'unknown'}
- **Confidence:** ${confidence}%

### Details
${exp.what || 'See vulnerability description.'}
${exp.why_it_matters ? `\n${exp.why_it_matters}` : ''}

### File
- \`${finding.file_path}\`${finding.line_range && finding.line_range.start ? ` (lines ${finding.line_range.start}-${finding.line_range.end})` : ''}

### Suggested Remediation
${manualSteps}${suggestedCode}

### References
- CWE: ${ref.cwe || 'N/A'}
- OWASP: ${ref.owasp || 'N/A'}

> This issue was created by the Specula autonomous security agent. Please review and remediate manually.
`;
}

module.exports = {
  getOctokit,
  extractOwnerRepo,
  getDefaultBranch,
  createBranch,
  resolveFix,
  newBranchName,
  buildPrBody,
  buildReportBody
};
