const {
  extractOwnerRepo,
  getOctokit,
  newBranchName,
  resolveFix,
  buildPrBody,
  buildReportBody
} = require('../routes/autofix-helpers');

describe('autofix-helpers', () => {
  describe('extractOwnerRepo', () => {
    test('parses full GitHub URL', () => {
      expect(extractOwnerRepo('https://github.com/octocat/Hello-World')).toEqual({
        owner: 'octocat',
        repo: 'Hello-World'
      });
    });

    test('strips trailing .git', () => {
      expect(extractOwnerRepo('https://github.com/owner/repo.git')).toEqual({
        owner: 'owner',
        repo: 'repo'
      });
    });

    test('returns nulls when no repo segment', () => {
      expect(extractOwnerRepo('https://github.com/octocat')).toEqual({
        owner: null,
        repo: null
      });
    });

    test('returns nulls for invalid url', () => {
      expect(extractOwnerRepo('not-a-url')).toEqual({ owner: null, repo: null });
    });
  });

  describe('newBranchName', () => {
    test('matches the fix/auto-patch-<hex> format', () => {
      expect(newBranchName()).toMatch(/^fix\/auto-patch-[0-9a-f]{6}$/);
    });

    test('produces unique names across calls', () => {
      const a = newBranchName();
      const b = newBranchName();
      expect(a).not.toBe(b);
    });
  });

  describe('getOctokit', () => {
    const original = process.env.GITHUB_TOKEN;

    afterEach(() => {
      if (original === undefined) delete process.env.GITHUB_TOKEN;
      else process.env.GITHUB_TOKEN = original;
    });

    test('returns null when GITHUB_TOKEN is unset', async () => {
      delete process.env.GITHUB_TOKEN;
      expect(await getOctokit()).toBeNull();
    });
  });

  describe('buildPrBody', () => {
    const finding = {
      prediction: 'sql_injection',
      severity: 'high',
      confidence: 0.87,
      explanation: { reference: { cwe: 'CWE-89', owasp: 'A03:2021' } },
      file_path: 'src/app.py'
    };

    test('includes vulnerability metadata', () => {
      const body = buildPrBody(finding, 'src/app.py', 'abcd1234');
      expect(body).toContain('sql_injection');
      expect(body).toContain('high');
      expect(body).toContain('87%');
      expect(body).toContain('src/app.py');
      expect(body).toContain('CWE-89');
      expect(body).toContain('A03:2021');
      expect(body).toContain('abcd1234');
    });

    test('includes the AI-generated disclaimer', () => {
      expect(buildPrBody(finding, 'src/app.py', 'a')).toContain('auto-generated by an AI');
    });
  });

  describe('buildReportBody', () => {
    const finding = {
      prediction: 'command_injection',
      severity: 'critical',
      confidence: 0.5,
      explanation: {
        reference: { cwe: 'CWE-78' },
        remediation: { guidance: 'Use safe exec APIs.' }
      },
      file_path: 'src/util.js',
      line_range: { start: 10, end: 12 }
    };

    test('uses no-fix messaging by default', () => {
      const body = buildReportBody(finding, 'no-fix');
      expect(body).toContain('no reliable fix');
      expect(body).toContain('CWE-78');
      expect(body).toContain('Use safe exec APIs.');
      expect(body).toContain('lines 10-12');
    });

    test('uses file-not-found messaging when the file is missing', () => {
      expect(buildReportBody(finding, 'file-not-found')).toContain('file was not found');
    });
  });

  describe('resolveFix', () => {
    test('returns the stored suggested_fix when present', async () => {
      const finding = { suggested_fix: 'SELECT * FROM users WHERE id=?', prediction: 'sql_injection' };
      expect(await resolveFix(finding, 'whatever')).toBe('SELECT * FROM users WHERE id=?');
    });

    test('returns null when no suggested_fix and the fix service is unreachable', async () => {
      const finding = { suggested_fix: null, prediction: 'sql_injection' };
      global.fetch = jest.fn().mockRejectedValue(new Error('down'));
      expect(await resolveFix(finding, 'some_code')).toBeNull();
      delete global.fetch;
    });

    test('returns null when suggested_fix is whitespace only', async () => {
      const finding = { suggested_fix: '   ', prediction: 'xss' };
      global.fetch = jest.fn().mockRejectedValue(new Error('down'));
      expect(await resolveFix(finding, 'code')).toBeNull();
      delete global.fetch;
    });
  });
});
